### ISSUE TITLE
RomFS support

### ISSUE THREAD

**Issue by FancyFurret** [switchpy/libnx-template#7]
Hello! Is it possible to add files to romfs in the built nro? I didn't see anything in the templates about how to do it. This would be really helpful so we can use this with GUI projects like borealis!

**Comment by vbe0201** [comment]
Hey there, romfs is indeed supported through a property named `ROMFS` on the build target. Its value may either be a path to a directory (in which case a fresh romfs image is built out of it) or a pre-built image to embed. If you're interested in the implementation, it can be found [in `cmake/SwitchTools.cmake`](https://github.com/vbe0201/switch-cmake/blob/rewrite/cmake/SwitchTools.cmake#L270).

To extend [this example](https://github.com/vbe0201/switch-cmake/blob/rewrite/templates/application/CMakeLists.txt), attaching romfs could look like the following:

```cmake
# Next, we need to set the required target properties
# so CMake can detect the metadata for the application.
set_target_properties(my_app PROPERTIES
        APP_TITLE "Template Application"
        APP_AUTHOR "Valentin B."
        APP_VERSION "0.1.0"
        ROMFS "/path/to/romfs")

...

# And finally we can add the actual binary (.nro) target.
add_nro_target(my_app)
```

**Comment by FancyFurret** [comment]
Oh sweet, thank you!
